name: CI
on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

jobs:
  build_meson:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Compile and Run Tests
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: .github/meson_build_env.yml
      - name: Compile argp
        shell: bash -l {0}
        if: runner.os != 'Windows'
        run: |
          meson setup build
          meson test -C build
      - name: Compile argp
        shell: cmd /C CALL {0}
        if: runner.os == 'Windows'
        run: |
          CALL micromamba activate meson_build_env
          meson setup build
          meson test -C build
